DBapprochBySP/Models/StudentData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBapprochBySP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentData()
        {
            this.ScholarshipDatas = new HashSet<ScholarshipData>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int RollNo { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipData> ScholarshipDatas { get; set; }
    }
}

DBapprochBySP/Models/StudentList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DBapprochBySP.Models
{
    public class StudentList
    {
        public int StudentId { get; set; }
        public Nullable<int> ScholarshipId { get; set; }
        public string Name { get; set; }
        public int RollNo { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Year { get; set; }

    }
}

DBapprochBySP/Controllers/StudentDataController.cs
using DBapprochBySP.Models;
using LanguageExt.ClassInstances;
using System;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;

namespace DBapprochBySP.Controllers
{
    public class StudentDataController : Controller
    {
        private readonly StudentEntities1 obj = new StudentEntities1();
        // GET: StudentData
        public ActionResult StudentList(int Cpage = 1)
        {

            ViewBag.PageCount = (int)Math.Ceiling((double)((decimal)obj.StudentDatas.Count() / 2));
            ViewBag.CPage = Cpage;
            var s = obj.Database.SqlQuery<StudentList>(
                "exec Pagination @PageNumber,@PageSize",
                new SqlParameter("@PageNumber", Cpage), new SqlParameter("@PageSize", 2)).ToList();


            /*IList<StudentList_Result> studentList = obj.StudentList().Select(x => new StudentList_Result()
            {
                Id = x.Id,
                Name = x.Name,
                RollNo = x.RollNo,
                Class = x.Class,
                City = x.City,
                Address = x.Address,
                Amount = x.Amount,
                Year = x.Year
            }).ToList();*/
             ViewBag.studentList = obj.StudentList().ToList();
            return View(s);
        }
        public ActionResult Edit(int id)
        {
            var st = obj.StudentList().FirstOrDefault(x=>x.Id==id);
            return View(st);

        }
        [HttpPost]
        public ActionResult Edit(StudentList_Result st)
        {
            obj.UpdateStudent(st.Id, st.Id,st.Name, st.RollNo, Int32.Parse(st.Class), st.City, st.Address, st.Amount, st.Year);
            return View();
        }


    }
}

DBapprochBySP/Views/StudentData/Edit.cshtml
@model DBapprochBySP.Models.StudentList_Result

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentList_Result</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RollNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RollNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RollNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Class, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Class, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Class, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DBapprochBySP/Views/StudentData/StudentList.cshtml
@*@model IEnumerable<DBapprochBySP.Models.StudentList_Result>*/*@
@{
    ViewBag.Title = "StudentList";
}
@{ 
    IEnumerable<DBapprochBySP.Models.StudentList_Result> Model = ViewBag.StudentList;
}

<h2>StudentList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("StudentList", "StudentData"))
{
    <table class="table">
        <tr>
            <th>
                ID
            </th>
            <th>
                Name
            </th>
            <th>
                RollNo
            </th>
            <th>
              Class
            </th>
            <th>
                Address
            </th>
            <th>
               City
            </th>
            <th>
                Amount
            </th>
            <th>
                Year
            </th>

            <th></th>
        </tr>
        @{ 
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.RollNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Class)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Amount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Year)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id}) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id})
                    </td>
                </tr>
               
            }
        }

    </table>

<table cellpadding="0" cellspacing="0">
    <tr>
        @* <td>
                <a class="pages" href="javascript:Prev()">Prev</a>
            </td>*@
        @for (int i = 1; i <= ViewBag.PageCount; i++)
        {
            <td>
                @if (i != ViewBag.CPage)
                {
                    <a class="pages" href="javascript:Goto(@i);">@i</a>
                }
                else
                {
                    <span class="pages">@i</span>
                }
            </td>
        }
        @*<td><a class="pages" href="javascript:Next();">Next</a></td>*@
    </tr>
</table>
    <input type="hidden" id="curpageidx" name="cPage" />
}
<script type="text/javascript">
    function Prev() {

        var idx = document.getElementById("curpageidx").value;

        if (idx - 1 > 0) {
            alert(idx);
            document.getElementById("curpageidx").a = idx - 1;
            document.forms[0].submit();
        }
    }
    function Goto(index) {
        document.getElementById("curpageidx").value = index;
        document.forms[0].submit();
    }
    function Next() {

        var idx = document.getElementById("curpageidx").value;
        alert(idx);
        if (idx + 1 <=@ViewBag.PageCount) {
            document.getElementById("curpageidx").value = idx - 1;
        document.forms[0].submit();
        }
    }
</script>